
spring:
  datasource:
    url: jdbc:h2:mem:workoutplanner
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
